spring:
  application:
    name: ms-users

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/muller
server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

fm:
  keycloak:
    serverUrl: http://localhost:8080
    clientId: keycloak-admin
    clientSecret: qj9GsnR3Qs796N5nKPJNlGGz2ehmLTE3
    realm: muller