# Configuraciones del servidor
server:
  port: 8090
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# Configuraciones de spring cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters: TokenRelay
      routes:
        - id: ms-bill
          uri: lb://ms-bill
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2

# Configuraciones de seguridad
  security:
    oauth2:
      client:
        provider:
          keycloak-project:
            issuer-uri: http://localhost:8080/realms/fm
        registration:
          keycloak-project:
            client-id: api-gateway-client
            client-secret: yFHSkjStJ8Hb6S3KZU0KeYPmW9AY6675
            authorization-grant-type: authorization-code
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak

